name: roomgraph
channels:
  - conda-forge
  - pytorch
dependencies:
  - black
  - flake8
  - isort
  - pip
  - setuptools
  - wheel
  - ipython
  - jupyter
  - pip:
      - python-dotenv
      # Need to compile from source until M1 conda binaries are released :(
      - git+https://github.com/rusty1s/pytorch_sparse@bc262e311f582c0591642490d6e71bc4ab636b7b
      - torch-sparse
      - torch-geometric
      # - torch-cluster -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
      # - torch-spline-conv -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
  - beautifulsoup4=4.11.1
  - geopandas=0.12.1
  - lxml=4.9.1
  - matplotlib=3.6.2
  - networkx=2.8.8
  - numpy=1.23.4
  - pandas=1.5.1
  - python=3.10
  - pytorch-lightning=1.7.7
  - pytorch=1.13.0
  - pyyaml=6.0
  - shapely=1.8.5
  - torchvision=0.14.0
